# Generated by Django 5.1.4 on 2024-12-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_country_hotel_address_en_hotel_address_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='hotel_imago',
            new_name='hotel_image',
        ),
    ]
